### ISSUE TITLE
Follow Dart style guide naming conventions

### ISSUE THREAD

**Issue by austincummings** [matthewfranglen/dart-ini#3] opened 2015-02-16 23:44 UTC
This is a bit nit-picky, but I think all Dart code should share the same naming conventions as defined in the [Dart style guide](https://www.dartlang.org/articles/style-guide/).

**Comment by matthewfranglen** [comment] 2015-02-17 12:42
Hi,

Thanks for the ticket.

The names are actually a direct duplicate of the [python ConfigParser methods](https://docs.python.org/2/library/configparser.html#rawconfigparser-objects). I was using that as a base to duplicate into Dart.

I do understand your point. After all, those method names do follow the python style guide (PEP-8). When in Rome etc.

I will update the library presently.

**Closed** 2015-02-19 19:07 UTC

**Comment by matthewfranglen** [comment] 2015-03-24 20:25
Support for the old method names has been removed as of version 1.1.0
